const {PGlite}=require('@electric-sql/pglite');const fs=require('fs'),assert=require('assert');
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333';
(async()=>{
 const db=new PGlite();await db.exec(`create role authenticated;create role anon;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);insert into auth.users values('${A}'),('${B}'),('${C}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated;grant execute on function auth.uid() to authenticated;`);
 const root='./';for(const name of ['SUPABASE_WATCH_PARTY.sql','supabase_watch_party_repair.sql','supabase_social_setup.sql','supabase_final_upgrade.sql','supabase_friends_party_upgrade.sql','supabase_friends_party_upgrade.sql','supabase_rc4_upgrade.sql','supabase_rc4_upgrade.sql','supabase_rc5_upgrade.sql','supabase_rc5_upgrade.sql'])await db.exec(fs.readFileSync(root+name,'utf8'));
 async function as(id){await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);`)}
 async function denied(sql){let fail=false;try{await db.exec(sql)}catch{fail=true}assert(fail,sql)}
 await as(A);await db.exec(`insert into miflix_social_profiles(user_id,nickname)values('${A}','randy');insert into miflix_watch_parties(room_code,host_user_id,state)values('123456','${A}','{}');select miflix_join_room('123456');select miflix_set_presence('Silo','tmdb:series:1',1,2,'123456');insert into miflix_friendships(sender_id,receiver_id)values('${A}','${B}');`);
 await as(B);assert.equal((await db.query('select * from miflix_friend_activity()')).rows.length,0);await db.exec(`insert into miflix_social_profiles(user_id,nickname)values('${B}','friend_b');update miflix_friendships set status='accepted' where receiver_id='${B}';`);
 const activity=(await db.query('select * from miflix_friend_activity()')).rows;assert.equal(activity[0].title,'Silo');assert.equal(activity[0].room_code,'123456');assert.equal(activity[0].online,true);
 assert.equal((await db.query("select miflix_request_access('123456') as state")).rows[0].state,'pending');await denied("select miflix_join_room('123456')");assert.equal((await db.query('select * from miflix_watch_parties')).rows.length,0);assert.equal((await db.query('select * from miflix_party_members')).rows.length,0);
 await denied(`select miflix_decide_access('123456','${B}',true)`);await denied(`select miflix_set_presence('Spoof','x',0,0,'123456')`);await denied('select * from miflix_presence');await denied('select * from miflix_party_access');
 await as(A);assert.equal((await db.query('select * from miflix_access_requests()')).rows[0].nickname,'friend_b');await db.exec(`select miflix_decide_access('123456','${B}',true)`);
 await as(B);assert.equal((await db.query("select miflix_request_access('123456') as state")).rows[0].state,'approved');await db.exec("select miflix_join_room('123456')");assert.equal((await db.query('select * from miflix_watch_parties')).rows.length,1);
 await db.exec("reset role;update miflix_watch_parties set state='{\"cloudId\":\"tmdb:series:1\",\"season\":1,\"episode\":2}' where room_code='123456';");
 await as(C);await denied("select miflix_request_playback('123456','tmdb:series:1',1,2,true)");
 await as(B);await denied("select miflix_request_playback('123456','tmdb:series:1',1,3,true)");await denied("select miflix_take_playback('123456')");
 await db.exec("select miflix_request_playback('123456','tmdb:series:1',1,2,true)");
 await as(A);assert.equal((await db.query("select miflix_take_pause('123456') as result")).rows[0].result,false);assert.equal((await db.query("select miflix_take_playback('123456') as result")).rows[0].result,true);assert.equal((await db.query("select miflix_take_playback('123456') as result")).rows[0].result,null);
 await as(B);await db.exec("select miflix_request_playback('123456','tmdb:series:1',1,2,true);select miflix_request_playback('123456','tmdb:series:1',1,2,false)");await as(A);assert.equal((await db.query("select miflix_take_playback('123456') as result")).rows[0].result,false);
 await as(B);await db.exec("select miflix_request_pause('123456','tmdb:series:1',1,2)");await as(A);assert.equal((await db.query("select miflix_take_playback('123456') as result")).rows[0].result,false);
 await as(B);await db.exec("select miflix_request_playback('123456','tmdb:series:1',1,2,true);delete from miflix_party_members where room_code='123456';");await as(A);assert.equal((await db.query("select miflix_take_playback('123456') as result")).rows[0].result,null);
 await as(B);assert.equal((await db.query("select miflix_request_access('123456') as state")).rows[0].state,'approved');await db.exec("select miflix_join_room('123456');select miflix_request_playback('123456','tmdb:series:1',1,2,true)");await db.exec("reset role;update miflix_party_pause_requests set created_at=now()-interval '31 seconds';");await as(A);assert.equal((await db.query("select miflix_take_playback('123456') as result")).rows[0].result,null);
 await as(B);await db.exec("select miflix_request_playback('123456','tmdb:series:1',1,2,true)");await db.exec("reset role;update miflix_watch_parties set state=jsonb_set(state,'{episode}','3') where room_code='123456';");await as(A);assert.equal((await db.query("select miflix_take_playback('123456') as result")).rows[0].result,null);
 await as(C);assert.equal((await db.query('select * from miflix_friend_activity()')).rows.length,0);await db.exec("select miflix_request_access('123456')");await denied("select miflix_join_room('123456')");await as(A);await db.exec(`select miflix_decide_access('123456','${C}',false)`);await as(C);assert.equal((await db.query("select miflix_request_access('123456') as state")).rows[0].state,'rejected');await denied("select miflix_join_room('123456')");
 await db.exec("reset role;update miflix_presence set updated_at=now()-interval '91 seconds';");await as(B);const offline=(await db.query('select * from miflix_friend_activity()')).rows[0];assert.equal(offline.online,false);assert.equal(offline.title,'');assert.equal(offline.room_code,null);
 await db.exec("reset role;update miflix_watch_parties set expires_at=now()-interval '1 second';");await as(B);await denied("select miflix_request_access('123456')");await denied("select miflix_join_room('123456')");
 await as(A);await db.exec(`insert into miflix_ratings(user_id,profile_id,cloud_id,score) values('${A}','p1','tmdb:movie:99',10),('${A}','p2','tmdb:movie:99',2);`);
 await denied(`insert into miflix_ratings(user_id,profile_id,cloud_id,score) values('${A}','p1','tmdb:movie:100',11);`);
 await denied(`insert into miflix_ratings(user_id,profile_id,cloud_id,score) values('${A}','p1','tmdb:movie:100',0);`);
 await denied(`insert into miflix_ratings(user_id,profile_id,cloud_id,score) values('${A}','p1','live:foo',7);`);
 assert.equal((await db.query("select score from miflix_ratings where profile_id='p1'")).rows[0].score,10);
 await as(B);assert.equal((await db.query('select * from miflix_ratings')).rows.length,0);await denied(`insert into miflix_ratings(user_id,profile_id,cloud_id,score) values('${A}','p1','tmdb:movie:99',1);`);
 await db.exec(`insert into miflix_ratings(user_id,profile_id,cloud_id,score)values('${B}','p1','tmdb:movie:99',8) on conflict(user_id,profile_id,cloud_id) do update set score=excluded.score;`);
 await as(A);assert.equal((await db.query("select score from miflix_ratings where profile_id='p1'")).rows[0].score,10);
 await db.exec(`update miflix_social_profiles set avatar_value='ai:fox' where user_id='${A}';`);await as(B);assert.equal((await db.query('select * from miflix_friend_activity()')).rows[0].avatar_value,'ai:fox');await as(C);assert.equal((await db.query('select * from miflix_friend_activity()')).rows.length,0);
 await db.close();console.log('PASS: repeatable migration; accepted friends only; private presence; pending cannot read/join; host-only approval; approved admission; rejection; heartbeat expiry; expired rooms blocked; guest pause/resume; host-only consumption; latest intent; stale media/requests; former member requests discarded; approved rejoin; ratings range/media validation; private account/profile ratings; friend avatars');
})().catch(e=>{console.error(e);process.exitCode=1});
